files: [
  {
    source: Translations.csv,
    translation: Translations.csv,
    first_line_contains_header: true,
    scheme: "identifier,source_phrase,context,none,zh-CN,zh-TW,fr,de,id,it,ja,ko,pt-PT,ru,es-ES"
  }
]