site_name: ColorPane
site_url: https://blupo.github.io/ColorPane
repo_name: Blupo/ColorPane
repo_url: https://github.com/Blupo/ColorPane

theme:
  name: material
  palette:
    scheme: slate
    primary: white
    accent: blue

extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - User Guide:
    - Color Editor: user-guide/color-editor.md
    - Gradient Editor: user-guide/gradient-editor.md
    - Color Properties: user-guide/color-properties.md
    - Tips and Tricks: user-guide/tips.md
  - Developer Guide:
    - API Integration: developer-guide/api-integration.md
    - Integration Examples: developer-guide/integration-examples.md
  - Technical:
    - Palette Format: technical/palette-format.md
    - API Reference: technical/api-reference.md 
  - Changelog: changelog.md
  - Attribution: attribution.md
  - Support ColorPane: support.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - toc:
      permalink: true