name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2.3.4
        with:
          submodules: true

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v1.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build
        run: rojo build --output ColorPane.rbxmx
      
      - name: Create
        uses: anton-yurchenko/git-release@v4.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: "docs/changelog.md"
        with:
          args: ./ColorPane.rbxmx