name: Create Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup Foreman
        uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build
        run: rojo build --output ColorPane.rbxmx
      
      - name: Create
        uses: anton-yurchenko/git-release@v3.4.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DRAFT_RELEASE: "false"
          PRE_RELEASE: "false"
          CHANGELOG_FILE: "changelog.md"
          ALLOW_EMPTY_CHANGELOG: "false"
          ALLOW_TAG_PREFIX: "true"
        with:
          args: ./ColorPane.rbxm