name: Development Code

on:
  push:
    branches:
      - develop
    paths-ignore:
      - "docs/**"
      - "mkdocs.yml"
      - "README.md"
      - "LICENSE"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: recursive

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: v0.3.0

      - name: Build ColorPane
        run: rojo build --output ColorPane.rbxm build/ColorPane.project.json

      - name: Build Companion
        run: rojo build --output Companion.rbxm build/Companion.project.json

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4.4.2
        with:
          name: Models
          path: |
            ColorPane.rbxm
            Companion.rbxm

      - name: Build and Upload ColorPane
        continue-on-error: true
        run: rojo upload --cookie "${{ secrets.ROBLOSECURITY }}" --asset_id ${{ vars.COLORPANE_WORKING_COPY_ASSET_ID }} build/ColorPane.project.json

      - name: Build and Upload Companion
        continue-on-error: true
        run: rojo upload --cookie "${{ secrets.ROBLOSECURITY }}" --asset_id ${{ vars.COMPANION_WORKING_COPY_ASSET_ID }} build/Companion.project.json
