name: Build and Deploy Release

on:
  push:
    tags:
      - v**

jobs:
  build:
    name: Create
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          submodules: true

      - name: Setup Aftman
        uses: ok-nick/setup-aftman@v0.4.2
        with:
          version: v0.3.0

      - name: Build ColorPane for Release
        run: rojo build --output ColorPane.rbxm build/ColorPane.project.json

      - name: Build Companion for Release
        run: rojo build --output Companion.rbxm build/Companion.project.json

      - name: Build and Upload ColorPane
        run: rojo upload --cookie "${{ secrets.ROBLOSECURITY }}" --asset_id "${{ vars.COLORPANE_ASSET_ID }}" build/ColorPane.project.json

      - name: Build and Upload Companion
        run: rojo upload --cookie "${{ secrets.ROBLOSECURITY }}" --asset_id "${{ vars.COMPANION_ASSET_ID }}" build/Companion.project.json

      - name: Create
        uses: anton-yurchenko/git-release@v4.2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CHANGELOG_FILE: "docs/changelog.md"
        with:
          args: ./ColorPane.rbxm
          args: ./Companion.rbxm
